package com.intraviologistica.intravio.model.enums;

public enum StatusPedido {

    PENDENTE, CANCELADO, SEPARADO, ENTREGUE_AO_TRANSPORTADOR, ROTEIRO_ENTREGA, EM_TRANSITO, ENTREGUE, RETORNO, RECEBIDO_CIDADE_DESTINO

}
